# Generated by Django 5.0.7 on 2024-07-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('reason', models.TextField()),
                ('accepted_appointment', models.BooleanField(default=False)),
            ],
        ),
    ]
