# Generated by Django 5.0.6 on 2024-06-30 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentist',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Dentist',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
