# Generated by Django 5.0.6 on 2024-07-01 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_dentist_user_id_remove_patient_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopInventory',
        ),
    ]
