# Generated by Django 5.0.6 on 2024-06-30 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_remove_dentist_user_id_remove_patient_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('dentist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
