# Generated by Django 5.0.7 on 2024-07-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='specialization',
            field=models.CharField(choices=[('restorative', 'Restorative'), ('cosmetic', 'Cosmetic')], max_length=100),
        ),
    ]
